export const ADD_TRAINER_REQUEST = "ADD_TRAINER_REQUEST";
export const ADD_TRAINER_SUCCESS = "ADD_TRAINER_SUCCESS";
export const ADD_TRAINER_FAILURE = "ADD_TRAINER_FAILURE";

export const GET_TRAINER_REQUEST = "GET_TRAINER_REQUEST";
export const GET_TRAINER_SUCCESS = "GET_TRAINER_SUCCESS";
export const GET_TRAINER_FAILURE = "GET_TRAINER_FAILURE";

export const REMOVE_TRAINER_REQUEST = "REMOVE_TRAINER_REQUEST";
export const REMOVE_TRAINER_SUCCESS = "REMOVE_TRAINER_SUCCESS";
export const REMOVE_TRAINER_FAILURE = "REMOVE_TRAINER_FAILURE";